FROM python:3.10-slim

WORKDIR /tests/functional

ENV PYTHONPATH=/tests/functional

RUN groupadd -r tester && useradd -d /tests/functional -r -g tester tester

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY --chown=tester:tester ./functional .

RUN mkdir -p /tests/functional/.pytest_cache && chown -R tester:tester /tests/functional/.pytest_cache
RUN chown -R tester:tester /tests/functional

USER tester
